# Generated by Django 4.0 on 2023-01-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chat_online_remove_message_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='msg_file'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='chat.chat'),
        ),
    ]
