# Generated by Django 4.0 on 2023-01-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_msg_file_message_msg_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_file', models.FileField(blank=True, default='', null=True, upload_to='msg_file')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.message')),
            ],
            options={
                'verbose_name': 'Message file',
                'verbose_name_plural': 'Message files',
                'db_table': 'message_file',
                'ordering': ('-message',),
            },
        ),
    ]
