# Generated by Django 4.0 on 2023-01-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_role'),
        ('chat', '0007_remove_message_msg_file_alter_message_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagefile',
            options={'ordering': ('-account',), 'verbose_name': 'Message file', 'verbose_name_plural': 'Message files'},
        ),
        migrations.RemoveField(
            model_name='messagefile',
            name='message',
        ),
        migrations.AddField(
            model_name='messagefile',
            name='account',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='account.account'),
            preserve_default=False,
        ),
    ]
