# Generated by Django 4.0 on 2023-01-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_messagefile_options_remove_messagefile_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unread',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
