# Generated by Django 4.0 on 2023-01-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='email',
            field=models.CharField(default='test@osperb.com', max_length=128),
        ),
    ]
