# Generated by Django 4.1.3 on 2022-11-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ('-date_added',), 'verbose_name': 'specilizations', 'verbose_name_plural': 'specilizations'},
        ),
    ]
