# Generated by Django 3.2 on 2022-12-08 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_alter_specialization_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specializations', to='student.student'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.CharField(blank=True, max_length=140, null=True)),
                ('company', models.CharField(max_length=140)),
                ('position', models.CharField(max_length=140)),
                ('job_description', models.CharField(max_length=140)),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('declined', 'Decline'), ('pending', 'Pending')], max_length=140)),
                ('last_date', models.CharField(blank=True, max_length=140, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'job_application',
                'verbose_name_plural': 'job_applications',
                'db_table': 'job_applications',
                'ordering': ('-date_added',),
            },
        ),
    ]
