# Generated by Django 3.2 on 2022-12-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='student.student'),
        ),
    ]
