# Generated by Django 4.1.3 on 2022-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnote',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
