# Generated by Django 4.1.3 on 2022-12-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentnote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
