# Generated by Django 4.0 on 2023-01-11 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_studentnote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='student.student'),
        ),
    ]
