# Generated by Django 4.0 on 2023-01-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_jobapplication_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='visa_end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='visa_start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
